### PR TITLE
feat: SAFE build for STAC AWS providers

### LINKED ISSUE #171: configure Sentinel SAFE build for AWS STAC API providers
After downloading a Sentinel product from STAC API providers (`astraea_eod`, `earth_search`) on AWS, build SAFE product the same way it is done for `aws_eos` (`S1_SAR_GRD`, `S2_MSI_L1C` and `S2_MSI_L2A`).

### PR DESCRIPTION
**Pull request by sbrunato**
fixes #171

### CODE REVIEW

**Comment by sbrunato** [comment]
@fahdben could you please checkout this branch to see if the implemented SAFE build for `S1_SAR_GRD` on `astraea_eod` is ok for you ?

**Comment by Fahdben** [comment]
The SAFE build for `S1_SAR_GRD` on `astraea_eod` works as expected! Thanks @sbrunato

**Comment by sbrunato** [comment]
`S2_MSI_L1C` & `S2_MSI_L2A` SAFE build have been added for `earth_search`.

To be able to search product by id, I have kept earth_search `id` (`S2A_41XMH_20210402_1_L2A`) as `EOProduct.properties["id"]`.

I used earth_search `sentinel:product_id` (`S2A_MSIL2A_20210402T103621_N0300_R008_T41XMH_20210402T112314`) as `EOProduct.properties["title"]` which is used as folder name when downloading.

**Comment by sbrunato** [comment]
Note that for `S2_MSI_L1C` products the file `./GRANULE/L1C_*/QI_DATA/*_PVI.jp2` is missing from AWS buckets. A warning will be raised when EODAG checks the SAFE build

**Pull request merged**
