### PR TITLE
fix(providers): missing orderable metadata mapping for some dedl product-types

### PR DESCRIPTION
**Pull request by amarandon**
- add orderable metadata mappings
- remove two obsolete product types: `SATELLITE_SEA_LEVEL_BLACK_SEA`,
      `SATELLITE_SEA_LEVEL_MEDITERRANEAN`
- fix productType for `GRIDDED_GLACIERS_MASS_CHANGE`

Ref #1355

### CODE REVIEW

**Comment by alambare** [comment]
pleae remove also those 2 products from WEkEO and from product_types.yaml file.

**Comment by amarandon** [comment]
I have a problem with COP_DEM_GLO90_DGED via dedl:

```
2024-10-24 16:06:25,195 eodag.download.http              [DEBUG   ] GET https://hda.data.destination-earth.eu/stac/collections/EO.DEM.DAT.COP-DEM_GLO-90-DGED/items/Copernicus_DSM_30_N43_00_E002_00.tar/download?provider=wekeo {'User-Agent': 'eodag/3.0.1.dev14+g56ebf31f.d20241022'} {}
Traceback (most recent call last):
  File "/home/amarando/Projects/eodag/eodag/plugins/download/http.py", line 192, in order_download
    response.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/amarando/venvs/dedl/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://hda.data.destination-earth.eu/stac/collections/EO.DEM.DAT.COP-DEM_GLO-90-DGED/items/Copernicus_DSM_30_N43_00_E002_00.tar/download?provider=wekeo

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/amarando/Projects/eodag/t.py", line 39, in <module>
    path = product.download()
  File "/home/amarando/Projects/eodag/eodag/api/product/_product.py", line 328, in download
    fs_path = self.downloader.download(
        self,
    ...<4 lines>...
        **kwargs,
    )
  File "/home/amarando/Projects/eodag/eodag/plugins/download/http.py", line 619, in download
    download_request(product, auth, progress_callback, wait, timeout, **kwargs)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amarando/Projects/eodag/eodag/plugins/download/base.py", line 621, in download_and_retry
    return download(*args, **kwargs)
  File "/home/amarando/Projects/eodag/eodag/plugins/download/http.py", line 612, in download_request
    for chunk in chunks:
                 ^^^^^^
  File "/home/amarando/Projects/eodag/eodag/plugins/download/http.py", line 903, in _stream_download
    self.order_download(product=product, auth=auth)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amarando/Projects/eodag/eodag/plugins/download/http.py", line 200, in order_download
    raise RequestError.from_error(e, message) from e
eodag.utils.exceptions.RequestError: ('Copernicus_DSM_30_N43_00_E002_00.tar could not be ordered', '{"description":"NotAvailableError: Could not find Copernicus_DSM_30_N43_00_E002_00.tar item in EO.DEM.DAT.COP-DEM_GLO-90-DGED collection for provider wekeo"}')
```

**Comment by amarandon** [comment]
Another problem with `FIRE_HISTORICAL` via `wekeo_ecmwf`:

```json
{"status_code":500,"title":"Search Product","detail":"Required param data_format missing"}
```

Wekeo's AI assistant is telling me this:

> ECMWF datasets have recently transitioned to new platforms, which include changes like replacing the 'format' parameter with 'data_format'. 

I tried setting the parameter when doing the search:
```py
search_result = dag.search(
    start="2016-03-01T00:00:00Z", end="2016-04-02T00:00:00Z",
    provider="wekeo_ecmwf", productType="FIRE_HISTORICAL",
    data_format="netcdf",
)
```

But it's not included in the query params:
```
2024-10-24 16:50:13,072 eodag.search.qssearch            [DEBUG   ] Query parameters:
{'dataset_id': 'EO:ECMWF:DAT:CEMS_FIRE_HISTORICAL_V1', 'year': ['2016'], 'month': ['03'], 'day': ['01'],
'product_type': 'reanalysis', 'variable': ['fire_danger_index'], 'system_version': ['4_1'], 'format': ['grib'],
'grid': 'original_grid', 'dataset_type': 'consolidated_dataset', 'itemsPerPage': 20, 'startIndex': 0}
```

I also tried updating the configuration of the product `FIRE_HISTORICAL` for the provider `wekeo_ecmwf` like this:

```py
    FIRE_HISTORICAL:
      productType: EO:ECMWF:DAT:CEMS_FIRE_HISTORICAL_V1
      providerProductType: reanalysis
      variable:
        - fire_danger_index
      version:
        - "4_1"
      data_format:
        - "grib"
        - "netcdf"
      # format:
      #   - "grib"
```
But data_format is not included in the request (note that in this case format is also removed):
```
2024-10-24 16:38:11,210 eodag.search.qssearch            [DEBUG   ] Query parameters:
{'dataset_id': 'EO:ECMWF:DAT:CEMS_FIRE_HISTORICAL_V1', 'year': ['2016'], 'month': ['03'], 'day': ['01'],
'product_type': 'reanalysis', 'variable': ['fire_danger_index'], 'system_version': ['4_1'], 'grid': 'original_grid',
'dataset_type': 'consolidated_dataset', 'itemsPerPage': 20, 'startIndex': 0}
```

**Comment by jlahovnik** [comment]
> Another problem with `FIRE_HISTORICAL` via `wekeo_ecmwf`:
> 
> ```json
> {"status_code":500,"title":"Search Product","detail":"Required param data_format missing"}
> ```
> 
> Wekeo's AI assistant is telling me this:
> 
> > ECMWF datasets have recently transitioned to new platforms, which include changes like replacing the 'format' parameter with 'data_format'.
> 
> I tried setting the parameter when doing the search:
> 
> ```python
> search_result = dag.search(
>     start="2016-03-01T00:00:00Z", end="2016-04-02T00:00:00Z",
>     provider="wekeo_ecmwf", productType="FIRE_HISTORICAL",
>     data_format="netcdf",
> )
> ```
> 
> But it's not included in the query params:
> 
> ```
> 2024-10-24 16:50:13,072 eodag.search.qssearch            [DEBUG   ] Query parameters:
> {'dataset_id': 'EO:ECMWF:DAT:CEMS_FIRE_HISTORICAL_V1', 'year': ['2016'], 'month': ['03'], 'day': ['01'],
> 'product_type': 'reanalysis', 'variable': ['fire_danger_index'], 'system_version': ['4_1'], 'format': ['grib'],
> 'grid': 'original_grid', 'dataset_type': 'consolidated_dataset', 'itemsPerPage': 20, 'startIndex': 0}
> ```
> 
> I also tried updating the configuration of the product `FIRE_HISTORICAL` for the provider `wekeo_ecmwf` like this:
> 
> ```python
>     FIRE_HISTORICAL:
>       productType: EO:ECMWF:DAT:CEMS_FIRE_HISTORICAL_V1
>       providerProductType: reanalysis
>       variable:
>         - fire_danger_index
>       version:
>         - "4_1"
>       data_format:
>         - "grib"
>         - "netcdf"
>       # format:
>       #   - "grib"
> ```
> 
> But data_format is not included in the request (note that in this case format is also removed):
> 
> ```
> 2024-10-24 16:38:11,210 eodag.search.qssearch            [DEBUG   ] Query parameters:
> {'dataset_id': 'EO:ECMWF:DAT:CEMS_FIRE_HISTORICAL_V1', 'year': ['2016'], 'month': ['03'], 'day': ['01'],
> 'product_type': 'reanalysis', 'variable': ['fire_danger_index'], 'system_version': ['4_1'], 'grid': 'original_grid',
> 'dataset_type': 'consolidated_dataset', 'itemsPerPage': 20, 'startIndex': 0}
> ```

If the parameter name has changed you have to update the metadata mapping of the provider: 
image

**Comment by amarandon** [comment]
> I have a problem with COP_DEM_GLO90_DGED via dedl:
> 
> ```
> 2024-10-24 16:06:25,195 eodag.download.http              [DEBUG   ] GET https://hda.data.destination-earth.eu/stac/collections/EO.DEM.DAT.COP-DEM_GLO-90-DGED/items/Copernicus_DSM_30_N43_00_E002_00.tar/download?provider=wekeo {'User-Agent': 'eodag/3.0.1.dev14+g56ebf31f.d20241022'} {}
> Traceback (most recent call last):
>   File "/home/amarando/Projects/eodag/eodag/plugins/download/http.py", line 192, in order_download
>     response.raise_for_status()
>     ~~~~~~~~~~~~~~~~~~~~~~~~~^^
>   File "/home/amarando/venvs/dedl/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status
>     raise HTTPError(http_error_msg, response=self)
> requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://hda.data.destination-earth.eu/stac/collections/EO.DEM.DAT.COP-DEM_GLO-90-DGED/items/Copernicus_DSM_30_N43_00_E002_00.tar/download?provider=wekeo
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/home/amarando/Projects/eodag/t.py", line 39, in <module>
>     path = product.download()
>   File "/home/amarando/Projects/eodag/eodag/api/product/_product.py", line 328, in download
>     fs_path = self.downloader.download(
>         self,
>     ...<4 lines>...
>         **kwargs,
>     )
>   File "/home/amarando/Projects/eodag/eodag/plugins/download/http.py", line 619, in download
>     download_request(product, auth, progress_callback, wait, timeout, **kwargs)
>     ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/amarando/Projects/eodag/eodag/plugins/download/base.py", line 621, in download_and_retry
>     return download(*args, **kwargs)
>   File "/home/amarando/Projects/eodag/eodag/plugins/download/http.py", line 612, in download_request
>     for chunk in chunks:
>                  ^^^^^^
>   File "/home/amarando/Projects/eodag/eodag/plugins/download/http.py", line 903, in _stream_download
>     self.order_download(product=product, auth=auth)
>     ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/amarando/Projects/eodag/eodag/plugins/download/http.py", line 200, in order_download
>     raise RequestError.from_error(e, message) from e
> eodag.utils.exceptions.RequestError: ('Copernicus_DSM_30_N43_00_E002_00.tar could not be ordered', '{"description":"NotAvailableError: Could not find Copernicus_DSM_30_N43_00_E002_00.tar item in EO.DEM.DAT.COP-DEM_GLO-90-DGED collection for provider wekeo"}')
> ```

Testing product COP_DEM_GLO90_DGED with various providers:
- :heavy_check_mark: creodias
- :heavy_check_mark: earth_search
- :heavy_check_mark: wekeo_main
- creodias_s3

**Comment by amarandon** [comment]
@jlahovnik As per recommandation from @alambare I'm removing the wekeo fix from this one and marking it as ready to review.

**Review by jlahovnik — APPROVED** [review]

**Review by sbrunato — APPROVED** [review]

**Pull request merged**
