### PR TITLE
feat: update wekeo sentinel product types

### PR DESCRIPTION
**Pull request by jlahovnik**
- adaptations on sentinel 1 product types
- add all available search parameters for all sentinel products
- add sentinel 3 and 6 products available in wekeo and not available in EODAG so far
- add wekeo to support providers list in documentation index page

### CODE REVIEW

**Review by sbrunato — CHANGES_REQUESTED** [review]
please 
- add `S1_SAR_OCN`, `S1_SAR_RAW`, `S2_MSI_L2AP`
- rename `*_REPROCESSED` product types to `*_BC00X`. 
Ex: `S3_SRA_1B_SE_REPROCESSED` to `S3_SRA_BS_BC004`

**Comment by jlahovnik** [comment]
> please
> 
>     * add `S1_SAR_OCN`, `S1_SAR_RAW`, `S2_MSI_L2AP`
> 
>     * rename `*_REPROCESSED` product types to `*_BC00X`.
>       Ex: `S3_SRA_1B_SE_REPROCESSED` to `S3_SRA_BS_BC004`

Updated

**Review by sbrunato — CHANGES_REQUESTED** [review]
- please use standard metadata parameters names: `relativeOrbitNumber` instead of `relorbit`, `platform` instead of `sat`, ...

**Comment by jlahovnik** [comment]
> please use standard metadata parameters names: `relativeOrbitNumber` instead of `relorbit`, `platform` instead of `sat`, ...

all changes done

**Review by sbrunato — CHANGES_REQUESTED** [review]
Please change properties:
- `type` to `providerProductType`
- `cycle` to `cycleNumber`

**Comment by jlahovnik** [comment]
> Please change properties:
> 
>     * `type` to `providerProductType`
> 
>     * `cycle` to `cycleNumber`

done

**Review by sbrunato — APPROVED** [review]

**Review by sbrunato — APPROVED** [review]

**Pull request merged**
